openapi: 3.0.0
info:
  title: Phareme API
  description: REST API documentation.
  version: 0.1.0

#_______________________________ ENDPOINT DEFINITIONS ________________________________  
paths:
  /categorie:
    # our controller name
    x-swagger-router-controller: categorie
    get:
      tags:
      - categorie
      operationId: getAll
      description: 
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetcategoriesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    post:
      tags:
      - categorie
      operationId: router.post
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/Categorie"
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/components/responses/schemas/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/components/responses/schemas/ErrorResponse"

  /categorie/{id}:
    # our controller name
    x-swagger-router-controller: categorie
    get:
      tags:
      - categorie    
      operationId: getOne
      description: get a categorie
      # define the success and error response
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetcategorieResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    put:
      tags:
      - categorie    
      operationId: update
      description: update a categorie
      # define the parameters
      parameters:
        - name: id
          description: categorie id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              allOf:                            
                - type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                - $ref: "#components/schemas/Categorie"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    delete:
      tags:
      - categorie    
      operationId: delete categorie
      description: delete a categorie
      # define the parameters
      parameters:
        - name: id
          description: categorie id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              
              properties:
                id:
                  type: string    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"

components:
  responses:
    schemas:
      GeneralResponse:
        $ref: "./docs/responses/errorResponse.yaml#/definitions/ErrorResponse"
      ErrorResponse:
        $ref: "./docs/responses/generalResponse.yaml#/definitions/GeneralResponse" 
      GetcategorieResponse:
        $ref: "./docs/schemas/categorie.yaml#/definitions/GetcategorieResponse"
      GetcategoriesListResponse:
        $ref: "./docs/schemas/categorie.yaml#/definitions/GetcategoriesListResponse" 
  
  schemas:    
    Categorie:
      $ref: "./docs/schemas/categorie.yaml#/definitions/Categorie"