openapi: 3.0.0
info:
  title: Phareme API
  description: REST API documentation.
  version: 0.1.0

#_______________________________ ENDPOINT DEFINITIONS ________________________________  
paths:
  /facture:
    # our controller name
    x-swagger-router-controller: facture
    get:
      tags:
      - facture
      operationId: getAll
      description: 
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetFactureListResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    post:
      tags:
      - facture
      operationId: router.post
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Facture"
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/components/responses/schemas/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/components/responses/schemas/ErrorResponse"

  /facture/{id}:
    # our controller name
    x-swagger-router-controller: facture
    get:
      tags:
      - facture    
      operationId: getOne
      description: get a facture
      # define the success and error response
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetFactureResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    put:
      tags:
      - facture    
      operationId: update
      description: update a facture
      # define the parameters
      parameters:
        - name: id
          description: facture id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              allOf:                            
                - type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                - $ref: "#/components/schemas/Facture"
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/components/responses/schemas/GeneralResponse'
        default:
          description: Error
          schema:
            $ref: '#/components/responses/schemas/ErrorResponse'
    delete:
      tags:
      - facture    
      operationId: delete facture
      description: delete a facture
      # define the parameters
      parameters:
        - name: id
          description: facture id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              
              properties:
                id:
                  type: string    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"

components:
  responses:
    schemas:
      GeneralResponse:
        $ref: "./docs/responses/errorResponse.yaml#/definitions/ErrorResponse"
      ErrorResponse:
        $ref: "./docs/responses/generalResponse.yaml#/definitions/GeneralResponse" 
      GetFactureListResponse:
        $ref: "./docs/schemas/facture.yaml#/definitions/GetFactureListResponse"
      GetFactureResponse:
        $ref: "./docs/schemas/facture.yaml#/definitions/GetFactureResponse" 
  
  schemas:    
    Facture:
      $ref: "./docs/schemas/facture.yaml#/definitions/Facture"       