openapi: 3.0.0
info:
  title: Phareme API
  description: REST API documentation.
  version: 0.1.0

#_______________________________ ENDPOINT DEFINITIONS ________________________________  
paths:
  /historique:
    # our controller name
    x-swagger-router-controller: historique
    get:
      tags:
      - historique
      operationId: getAll
      description: 
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetHistoriquesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    post:
      tags:
      - historique
      operationId: router.post
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Historique"
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/components/responses/schemas/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/components/responses/schemas/ErrorResponse"

  /historique/{id}:
    # our controller name
    x-swagger-router-controller: historique
    get:
      tags:
      - historique    
      operationId: getOne
      description: get a historique
      # define the success and error response
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GethistoriqueResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    put:
      tags:
      - historique    
      operationId: update
      description: update a historique
      # define the parameters
      parameters:
        - name: id
          description: historique id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              allOf:                            
                - type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                - $ref: "#/components/schemas/Historique"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    delete:
      tags:
      - historique    
      operationId: delete historique
      description: delete a historique
      # define the parameters
      parameters:
        - name: id
          description: historique id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              
              properties:
                id:
                  type: string    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"

components:
  responses:
    schemas:
      GeneralResponse:
        $ref: "./docs/responses/errorResponse.yaml#/definitions/ErrorResponse"
      ErrorResponse:
        $ref: "./docs/responses/generalResponse.yaml#/definitions/GeneralResponse" 
      GetHistoriquesListResponse:
        $ref: "./docs/schemas/historique.yaml#/definitions/GetHistoriquesListResponse"
      GethistoriqueResponse:
        $ref: "./docs/schemas/historique.yaml#/definitions/GethistoriqueResponse" 
  
  schemas:    
    Historique:
      $ref: "./docs/schemas/historique.yaml#/definitions/Historique"             