openapi: 3.0.0
info:
  title: Phareme API
  description: REST API documentation.
  version: 0.1.0

#_______________________________ ENDPOINT DEFINITIONS ________________________________  
paths:
  /api/residence:
    # our controller name
    x-swagger-router-controller: residence
    get:
      tags:
      - residence
      operationId: getAll
      description: 
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetResidencesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    post:
      tags:
      - residence
      operationId: router.post
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Residence"
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/components/responses/schemas/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/components/responses/schemas/ErrorResponse"

  /api/residence/{id}:
    # our controller name
    x-swagger-router-controller: residence
    get:
      tags:
      - residence    
      operationId: getOne
      description: get a residence
      # define the success and error response
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetResidenceResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    put:
      tags:
      - residence    
      operationId: update
      description: update a residence
      # define the parameters
      parameters:
        - name: id
          description: residence id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              allOf:                            
                - type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                - $ref: "#/components/schemas/Residence"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    delete:
      tags:
      - residence    
      operationId: delete residence
      description: delete a residence
      # define the parameters
      parameters:
        - name: id
          description: residence id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              
              properties:
                id:
                  type: string    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"

components:
  responses:
    schemas:
      GeneralResponse:
        $ref: "./docs/responses/errorResponse.yaml#/definitions/ErrorResponse"
      ErrorResponse:
        $ref: "./docs/responses/generalResponse.yaml#/definitions/GeneralResponse" 
      GetResidencesListResponse:
        $ref: "./docs/schemas/residence.yaml#/definitions/GetResidencesListResponse"
      GetResidenceResponse:
        $ref: "./docs/schemas/residence.yaml#/definitions/GetResidenceResponse" 
  
  schemas:    
    Residence:
      $ref: "./docs/schemas/residence.yaml#/definitions/Residence"           