openapi: 3.0.0
info:
  title: Phareme API
  description: REST API documentation.
  version: 0.1.0

#_______________________________ ENDPOINT DEFINITIONS ________________________________  
paths:
  /sizes:
    # our controller name
    x-swagger-router-controller: sizes
    get:
      tags:
      - sizes
      operationId: getAll
      description: 
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetsizesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    post:
      tags:
      - sizes
      operationId: router.post
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sizes"
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/components/responses/schemas/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/components/responses/schemas/ErrorResponse"

  /sizes/{id}:
    # our controller name
    x-swagger-router-controller: sizes
    get:
      tags:
      - sizes    
      operationId: getOne
      description: get a sizes
      # define the success and error response
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GetSizesResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    put:
      tags:
      - sizes    
      operationId: update
      description: update a sizes
      # define the parameters
      parameters:
        - name: id
          description: sizes id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              allOf:                            
                - type: object
                  required:
                  - id
                  properties:
                    id:
                      type: string
                - $ref: "#/components/schemas/Sizes"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"
    delete:
      tags:
      - sizes    
      operationId: delete sizes
      description: delete a sizes
      # define the parameters
      parameters:
        - name: id
          description: sizes id
          type: string
          in: path
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              
              properties:
                id:
                  type: string    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/components/responses/schemas/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/components/responses/schemas/ErrorResponse"

components:
  responses:
    schemas:
      GeneralResponse:
        $ref: "./docs/responses/errorResponse.yaml#/definitions/ErrorResponse"
      ErrorResponse:
        $ref: "./docs/responses/generalResponse.yaml#/definitions/GeneralResponse" 
      GetsizesListResponse:
        $ref: "./docs/schemas/sizes.yaml#/definitions/GetsizesListResponse"
      GetSizesResponse:
        $ref: "./docs/schemas/sizes.yaml#/definitions/GetSizesResponse" 
  
  schemas:    
    Sizes:
      $ref: "./docs/schemas/sizes.yaml#/definitions/Sizes"             